spring:
  application:
    name: recipeApi

  datasource:
      url: jdbc:postgresql://localhost:5432/recipe
      username: root
      password: 12345678
      driver-class-name: org.postgresql.Driver

  redis:
    host: redis
    port: 6379
    timeout: 2000

  jpa:
    hibernate:
      ddl-auto: update

  security:
    jwt:
      secret-key: nYGarGcYQyVQwIoJUw6F8Q6b70ZIjPIN
      expiration-time: 86400000

server:
  port: 8080